[package]
name = "kana-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.6", features = ["csr"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
gloo-net = "0.5"
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
js-sys = "0.3.83"
