[package]
name = "kana-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
dotenvy = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ratatui = "0.29.0"
crossterm = "0.28.1"
unicode-width = "0.1"
textwrap = "0.16"
rand = "0.8"
color-eyre = "0.6"
thiserror = "2.0"
chrono = { version = "0.4.42", features = ["serde"] }
